### ISSUE TITLE
依存ライブラリ類をDockerイメージ内に含める

### ISSUE THREAD

**Issue by ttoda31** [takenaka-ai/webapp-handson#2]
現在の設定では、Dockerコンテナの起動時に依存ライブラリをインストールし開発環境が構築されるようになっています。
（`docker-compose.yaml`内の`npm install`と`pip install`）

予め依存ライブラリをインストールしたDockerイメージを作成しておき、下記の様にコンテナ起動時には最終的に実行したいコマンドだけを叩く方が一般的かと思います。
```yaml
# docker-compose.yamlからインストールコマンドを抜いた例

version: '3.9'
services:
  frontend:
    ...
    command: npm run dev
    ...
  backend:
    ...
    command: uvicorn main:app --reload --host 0.0.0.0
    ...
```
「FastAPI Vue3 docker compose」などでググると、たくさん実例が見つかると思います。

但し、フロントエンドのDocker開発環境構築については結構ややこしい面もあるので注意が必要です。
「node_modules docker」とかでググると色々参考記事が出てきますが、Dockerの仕様に関する十分な理解が必要です。
また、「Volume Trick」と呼ばれるDockerのテクニックで対処するのが一般的です。
